[build]
  publish = "dist"
  command = "npm run build"

[context.production.environment]
  NODE_VERSION = "v16.14.0"
  HUGO_VERSION = "v0.88.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
